//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerModules.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Contributions = new HashSet<Contribution>();
        }
    
        public string Pin { get; set; }
        public string RegistrationCode { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MobileNumber { get; set; }
        public string MobileNumber2 { get; set; }
        public string Email { get; set; }
        public string Employer_Recno { get; set; }
        public string HomeAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<decimal> FundId { get; set; }
        public string ClientStatus { get; set; }
        public string AGENT_CODE { get; set; }
        public string Employer_name { get; set; }
        public string Account_Officer { get; set; }
        public string Account_Officer_Mobile { get; set; }
        public string Account_Officer_Email { get; set; }
        public string Employer_Statecode { get; set; }
        public string Bvn { get; set; }
        public string Nin { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<bool> IsNigerian { get; set; }
        public string HouseNo { get; set; }
        public string StreetName { get; set; }
        public string LGACode { get; set; }
        public string StateCode { get; set; }
        public string CountryCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contribution> Contributions { get; set; }
    }
}
