//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerModules.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PALSiteDBEntities : DbContext
    {
        public PALSiteDBEntities()
            : base("name=PALSiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployerDetail> EmployerDetails { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Remark> Remarks { get; set; }
        public virtual DbSet<ScheduleHeader> ScheduleHeaders { get; set; }
        public virtual DbSet<ScheduleHeaderTemp> ScheduleHeaderTemps { get; set; }
        public virtual DbSet<ScheduleUpload> ScheduleUploads { get; set; }
        public virtual DbSet<ScheduleUploadTemp> ScheduleUploadTemps { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULES { get; set; }
        public virtual DbSet<Pfa> Pfas { get; set; }
        public virtual DbSet<MasterSchedule> MasterSchedules { get; set; }
        public virtual DbSet<PaymentProve> PaymentProves { get; set; }
        public virtual DbSet<Contribution> Contributions { get; set; }
    }
}
